
const ContentData =[
    {
        id:1,
        img: "/images/portfolio1.png",
        headline: "december, 2018",
        p1:"Pure Bedroom Architecture",
        p2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.",
        p2_extended: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.  Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora inci dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur.",
        category:" Hi-tech",
        architects: "Achima Rut",
        years: "2019",
        area:"50m2",
        project_Architect:"Yuko Tonogi",
        design_Team:"Kohei Oba , Masatoshi Sugiyama",
        structural_Engineer:"Masato Araya (OAK), Takashi Manda (tmsd), Taijiro Kato (tmsd)",
        construction:"Akira Ohara, Satoshi Kikuchi (Oharakomusho)",
        city:"Toshima",
        country:"Japan",
    },
    {
        id:2,
        img: "/images/portfolio2.png",
        headline: "december, 2018",
        p1:"Pure Bedroom Architecture",
        category:" Suburb",
        p2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.",
        p2_extended: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.  Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora inci dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur.",
        architects: "Mark Wilkinson",
        years: "2020",
        area:"45m2",
        project_Architect:"Chester Dorsey",
        design_Team:"Brice Reveves, Brian Curtis",
        structural_Engineer:"Eric Garrison, Daniel Hicks, Taijiro Kato",
        construction:"Doroty Russel, Rose Sharell",
        city:"New York",
        country:"America",
    },
    {
        id:3,
        img: "/images/portfolio3.png",
        headline: "december, 2018",
        p1:"Pure Bedroom Architecture",
        p2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.",
        category:" Digital architecture",
        p2_extended: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.  Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora inci dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur.",
        architects: "Achima Rut",
        years: "2017",
        area:"180m2",
        project_Architect:"Joseph Robert",
        design_Team:"Prosper Green , Kristina Gregory",
        structural_Engineer:"Donna Page, Giles Arnold, Annice Walker",
        construction:"Akira Ohara, Satoshi Kikuchi",
        city:"Toronto",
        country:"America",

    },
    {
        id:4,
        img: "/images/portfolio4.png",
        headline: "december, 2018",
        p1:"Pure Bedroom Architecture",
        category:" Suburb",
        p2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.",
        p2_extended: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.  Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora inci dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur.",
        architects: "Austin Woods",
        years: "2018",
        area:"70m2",
        project_Architect:"Mark Wilkinson",
        design_Team:"Kohei Oba , Masatoshi Sugiyama",
        structural_Engineer:"Masato Araya (OAK), Takashi Manda (tmsd), Taijiro Kato (tmsd)",
        construction:"Akira Ohara, Satoshi Kikuchi (Oharakomusho)",
        city:"Toshima",
        country:"Japan",

    },
    {
        id:5,
        img: "/images/portfolio5.png",
        headline: "december, 2018",
        p1:"Pure Bedroom Architecture",
        category:" Digital architecture",
        p2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.",
        p2_extended: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.  Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora inci dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur.",
        architects: "Austin Woods",
        years: "2018",
        area:"70m2",
        project_Architect:"Mark Wilkinson",
        design_Team:"Kohei Oba , Masatoshi Sugiyama",
        structural_Engineer:"Masato Araya (OAK), Takashi Manda (tmsd), Taijiro Kato (tmsd)",
        construction:"Akira Ohara, Satoshi Kikuchi (Oharakomusho)",
        city:"Toshima",
        country:"Japan",

    },
    {
        id:6,
        img: "/images/portfolio6.png",
        headline: "december, 2018",
        p1:"Pure Bedroom Architecture",
        category:" Deconstructivism",
        p2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.",
        p2_extended: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.  Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora inci dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur.",
        architects: "Austin Woods",
        years: "2018",
        area:"70m2",
        project_Architect:"Mark Wilkinson",
        design_Team:"Kohei Oba , Masatoshi Sugiyama",
        structural_Engineer:"Masato Araya (OAK), Takashi Manda (tmsd), Taijiro Kato (tmsd)",
        construction:"Akira Ohara, Satoshi Kikuchi (Oharakomusho)",
        city:"Toshima",
        country:"Japan",

    },
    {
        id:7,
        img: "/images/portfolio7.png",
        headline: "december, 2018",
        p1:"Pure Bedroom Architecture",
        category:" Hi-tech",
        p2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.",
        p2_extended: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae fugit dicta odio officia facere, quos reiciendis. Molestiae fugit dicta.  Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora inci dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur.",
        architects: "Austin Woods",
        years: "2018",
        area:"70m2",
        project_Architect:"Mark Wilkinson",
        design_Team:"Kohei Oba , Masatoshi Sugiyama",
        structural_Engineer:"Masato Araya (OAK), Takashi Manda (tmsd), Taijiro Kato (tmsd)",
        construction:"Akira Ohara, Satoshi Kikuchi (Oharakomusho)",
        city:"Toshima",
        country:"Japan",

    }
]

export const getCategoryMap = (array) =>{
    return array.reduce((accMap, item) => ({
        ...accMap,
        [item.id]:item
    }),{})
}
export default ContentData